name: "Replay Verify"
description: |
  Runs the replay-verify tool from aptos-core, assuming it is already checked out in the current working directory.
inputs:
  BUCKET:
    description: "The name of the bucket to download the ledger from."
    required: true
  SUB_DIR:
    description: "The subdirectory of the bucket to download the ledger from."
    required: true
  HISTORY_START:
    description: "The starting history index to replay from."
    required: true
  TXNS_TO_SKIP:
    description: "A list of transaction indices to skip during replay."
    required: true
  BACKUP_CONFIG_TEMPLATE_PATH:
    description: "The path to the backup config template to use."
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/rust-setup

    - name: Install AWS CLI
      shell: bash
      run: |
        scripts/dev_setup.sh -b -i awscli
        echo "${HOME}/bin/" >> $GITHUB_PATH # default INSTALL_DIR to path

    - name: Build CLI binaries in release mode
      shell: bash
      run: cargo build --release -p aptos-backup-cli --bin replay-verify --bin db-backup

    - name: Run replay-verify in parallel
      shell: bash
      run: scripts/replay-verify/replay_verify.py
      env:
        BUCKET: ${{ inputs.BUCKET }}
        SUB_DIR: ${{ inputs.SUB_DIR }}
        HISTORY_START: ${{ inputs.HISTORY_START }}
        TXNS_TO_SKIP: ${{ inputs.TXNS_TO_SKIP }}
        BACKUP_CONFIG_TEMPLATE_PATH: ${{ inputs.BACKUP_CONFIG_TEMPLATE_PATH }}
