# This defines a workflow to verify all modules that have been published on chain with the latest aptos node software.
# In order to trigger it go to the Actions Tab of the Repo, click "Verify Modules" and then "Run Workflow".

name: "verify-modules-testnet"
on:
  # Allow triggering manually
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: false
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
  pull_request:
    paths:
      - ".github/workflows/module-verify-testnet.yaml"

env:
  BUCKET: aptos-testnet-backup-2223d95b
  SUB_DIR: e1
  CONFIG_TEMPLATE_NAME: s3-public.yaml

jobs:
  module-verify:
    timeout-minutes: 720
    runs-on: high-perf-docker-with-local-ssd
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}
      - uses: ./.github/actions/module-verify
        with:
          BUCKET: aptos-testnet-backup-2223d95b
          SUB_DIR: e1
          CONFIG_TEMPLATE_NAME: s3-public.yaml
