name: "replay-LLT-transactions-nightly"
on:
  # Allow triggering manually
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: false
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
  schedule:
    - cron: "5 9/12 * * *"
  pull_request:
    paths:
      - ".github/workflows/replay-verify-testnet.yaml"

jobs:
  replay-transactions:
    # if we're running on a PR, it's only for testing purposes, so we can set a shorter timeout
    timeout-minutes: ${{ github.event_name == 'pull_request' && 20 || 720 }}
    runs-on: high-perf-docker-with-local-ssd
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: ./.github/actions/replay-verify
        with:
          BUCKET: aptos-testnet-backup-2223d95b
          SUB_DIR: e1
          HISTORY_START: 350000000 # TODO: We need an exhaustive list of txns_to_skip before we can set this to 0.
          TXNS_TO_SKIP: 46874937 151020059 409163615 409163669 409163708 409163774 409163845 409163955 409164059 409164191 414625832
          BACKUP_CONFIG_TEMPLATE_PATH: terraform/helm/fullnode/files/backup/s3-public.yaml
