name: "replay-mainnet-transactions-nightly"
on:
  # Allow triggering manually
  workflow_dispatch:
    inputs:
      GIT_SHA:
        required: false
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
  schedule:
    - cron: "0 9/12 * * *"
  pull_request:
    paths:
      - ".github/workflows/replay-verify-mainnet.yaml"

jobs:
  replay-verify:
    # if we're running on a PR, it's only for testing purposes, so we can set a shorter timeout
    timeout-minutes: ${{ github.event_name == 'pull_request' && 20 || 720 }}
    runs-on: high-perf-docker-with-local-ssd
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: ./.github/actions/replay-verify
        with:
          BUCKET: aptos-mainnet-backup-backup-831a69a8
          SUB_DIR: e1
          HISTORY_START: 0
          TXNS_TO_SKIP: 12253479 12277499
          BACKUP_CONFIG_TEMPLATE_PATH: terraform/helm/fullnode/files/backup/s3-public.yaml
